# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to Firebase App Distribution"
  lane :beta do
    # See https://docs.fastlane.tools/actions/match/#parameters for docs
    match(
      type: "adhoc",
      # GITHUB_TOKEN is a PAT that has access to the match repository 
      # GITHUB_USERNAME is the username of the user who generated the above access token
      git_basic_authorization: Base64.strict_encode64("#{'GITHUB_USERNAME'}:#{ENV['GITHUB_TOKEN']}"),
      # This makes it so it cannot create credentials if they are not there
      readonly: true,
    )

    build_app

    firebase_app_distribution(
      app: "1:891497953282:ios:ef4d96cd5d4680e4338f1b",
      groups: "ios-testers"
    )
  end
end
