name: Production

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Checkout and prep
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: { node-version: "12" }

      # Install
      - uses: bahmutov/npm-install@v1
        with: { working-directory: "app" }
      - uses: bahmutov/npm-install@v1
        with: { working-directory: "functions" }
      - uses: bahmutov/npm-install@v1
        with: { working-directory: "native-audio" }
      - uses: bahmutov/npm-install@v1

      # Patching
      - run: npx patch-package
      - run: npx patch-package
        working-directory: app

      # Building
      - run: npm run build
        working-directory: functions
      - run: npm run build
        working-directory: native-audio
      - run: npm run build:web-production
        working-directory: app
        env: { SENTRY_AUTH_TOKEN: "${{ secrets.SENTRY_AUTH_TOKEN }}" }

      # Deployment
      # PRODUCTION_FIREBASE_TOKEN generated using "firebase login:ci"
      # PRODUCTION_FIREBASE_TOKEN is for Gray Wolf
      - run: npx firebase deploy --project production
        env: { FIREBASE_TOKEN: "${{ secrets.PRODUCTION_FIREBASE_TOKEN }}" }

  deploy_mobile:
    # Make this separate since it has to use macOS which costs 10x as much as ubuntu
    runs-on: macOS-latest
    timeout-minutes: 10
    steps:
      # Checkout and prep
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: { node-version: "12" }
      - uses: actions/setup-ruby@v1
      - working-directory: app
        # Install the same version of bundler that I used
        # or else bundle install fails...
        run: |
          gem install bundler:1.17.2
          bundle install

      # Install
      - uses: bahmutov/npm-install@v1
        with: { working-directory: "app" }
      - uses: bahmutov/npm-install@v1
        with: { working-directory: "functions" }
      - uses: bahmutov/npm-install@v1
        with: { working-directory: "native-audio" }
      - uses: bahmutov/npm-install@v1

      # Patching
      - run: npx patch-package
      - run: npx patch-package
        working-directory: app

      # Building
      - run: npm run build
        working-directory: native-audio
      - run: npm run build:mobile-production
        env: { SENTRY_AUTH_TOKEN: "${{ secrets.SENTRY_AUTH_TOKEN }}" }
        working-directory: app
      - run: npx cap sync
        working-directory: app

      - run: fastlane beta
        working-directory: app/ios/App
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GIT_ACCESS_TOKEN }}
          GITHUB_USERNAME: jsmith
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      - run: fastlane beta
        working-directory: app/android
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
