name: Staging

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Checkout and prep
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: { node-version: "12" }
      - run: ./.github/scripts/decrypt.sh
        env: { GPG_PASSWORD: "${{ secrets.GPG_PASSWORD }}" }

      # Install
      - uses: bahmutov/npm-install@v1
        with: { working-directory: "app" }
      - uses: bahmutov/npm-install@v1
        with: { working-directory: "functions" }
      - uses: bahmutov/npm-install@v1
        with: { working-directory: "native-audio" }
      - uses: bahmutov/npm-install@v1

      # Building
      - run: npm run build
        working-directory: functions
      - run: npm run build
        working-directory: native-audio
      - run: npm run build:web-staging
        working-directory: app
        env: { SENTRY_AUTH_TOKEN: "${{ secrets.SENTRY_AUTH_TOKEN }}" }

      # Deployment
      # PRODUCTION_FIREBASE_TOKEN generated using "firebase login:ci"
      - run: npx firebase deploy --project staging
        env: { FIREBASE_TOKEN: "${{ secrets.PRODUCTION_FIREBASE_TOKEN }}" }
