name: Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    # Typically it takes ~ 4 minutes to run all of the checks :)
    timeout-minutes: 5

    steps:
      # Checkout and prep
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: { node-version: "12" }
      - run: ./.github/scripts/decrypt.sh
        env: { GPG_PASSWORD: "${{ secrets.GPG_PASSWORD }}" }

      # Install
      - uses: bahmutov/npm-install@v1
        with: { working-directory: "app" }
      - uses: bahmutov/npm-install@v1
        with: { working-directory: "functions" }
      - uses: bahmutov/npm-install@v1
        with: { working-directory: "native-audio" }
      - uses: bahmutov/npm-install@v1

      # Patching
      - run: npx patch-package
        working-directory: app

      # Building
      - run: npm run build
        working-directory: native-audio

      # Finally, run the checks!
      - run: npm run checks
