name: Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    # Typically it takes less than 2 minutes to run all of the checks :)
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      
      - run: ./.github/scripts/decrypt.sh
        env:
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          GOOGLE_KEY_GPG_PASS: ${{ secrets.GOOGLE_KEY_GPG_PASS }}

      - run: npm install --no-package-lock
      - run: npm run bootstrap
      - run: npx patch-package
      - run: npm run check:formatting
      - run: npm run check:lint
      # Not type checking because testing actually type checks
      # - run: npm run check:types
      - run: npm run test
