name: Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    # Typically it takes ~ 3 minutes to run all of the checks :)
    timeout-minutes: 4

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - uses: actions/setup-node@v1
        with: { node-version: "11.x" }
      - run: ./.github/scripts/decrypt.sh
        env:
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          GOOGLE_KEY_GPG_PASS: ${{ secrets.GOOGLE_KEY_GPG_PASS }}

      - run: make install-ci
      - run: npm install --no-save firebase-tools
      - run: npm run build
        working-directory: native-audio
      - run: npx patch-package
      - run: npx patch-package
        working-directory: app
      - run: make checks
